//  AUTH
export const AUTH = "AUTH ";
export const LOGOUT = "LOGOUT";

// USERS
export const FETCH_USER_ID = "FETCH_USER_ID";
export const FETCH_USER = "FETCH_USER";

// ALL QUESTIONS
export const FETCH_QUESTIONS = "FETCH_CATEGORY_QUESTIONS ";

// TEST
export const CREATE_TEST = "CREATE_TEST ";
export const FETCH_TESTS = "FETCH_TESTS ";
export const FETCH_TEST_ID = " FETCH_TEST_ID ";
export const UPDATE_TEST = "  UPDATE_TEST ";
export const DELETE_TEST = "DELETE_TEST";

// CATEGORY QUESTION
export const CREATE_CATEGORY_QUESTION = "CREATE_CATEGORY_QUESTION ";
export const FETCH_CATEGORY_QUESTIONS = "FETCH_CATEGORY_QUESTIONS ";
export const FETCH_CATEGORY_QUESTION_ID = " FETCH_CATEGORY_QUESTION_ID ";
export const UPDATE_CATEGORY_QUESTION = "  UPDATE_CATEGORY_QUESTION ";
export const DELETE_CATEGORY_QUESTION = "DELETE_CATEGORY_QUESTION";

// CLOZE QUESTION
export const CREATE_CLOZE_QUESTION = "CREATE_CLOZE_QUESTION ";
export const FETCH_CLOZE_QUESTIONS = "FETCH_CLOZE_QUESTIONS ";
export const FETCH_CLOZE_QUESTION_ID = " FETCH_CLOZE_QUESTION_ID ";
export const UPDATE_CLOZE_QUESTION = "  UPDATE_CLOZE_QUESTION ";
export const DELETE_CLOZE_QUESTION = "DELETE_CLOZE_QUESTION";

// PASSAGE QUESTION
export const CREATE_PASSAGE_QUESTION = "CREATE_PASSAGE_QUESTION ";
export const FETCH_PASSAGE_QUESTIONS = "FETCH_PASSAGE_QUESTIONS ";
export const FETCH_PASSAGE_QUESTION_ID = " FETCH_PASSAGE_QUESTION_ID ";
export const UPDATE_PASSAGE_QUESTION = "  UPDATE_PASSAGE_QUESTION ";
export const DELETE_PASSAGE_QUESTION = "DELETE_PASSAGE_QUESTION";
